version: '3.5'
services:
  ganache-stacktical:
    image: trufflesuite/ganache-cli:v6.12.1
    ports:
      - 8545:8545
    volumes:
      - ./ganache/db:/chainlink/ganache-db
    networks:
      - dsla-test
    command: --accounts 10 --quiet --defaultBalanceEther 100000 -d --db=/chainlink/ganache-db -i 1337 --blockTime=2

  postgres-stacktical:
    image: postgres:13.1
    volumes:
      - ./postgres/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chainlink
    networks:
      - dsla-test

  chainlink-stacktical:
    image: smartcontract/chainlink:0.9.6
    ports:
      - 6688:6688
    volumes:
      - ./chainlink:/chainlink
      - ./chainlink/.api:/chainlink/.api
      - ./chainlink/.password:/chainlink/.password
    environment:
      - ROOT=/chainlink
      - ETH_CHAIN_ID=1337
      - LOG_LEVEL=debug
      - MIN_INCOMING_CONFIRMATIONS=0
      - MIN_OUTGOING_CONFIRMATIONS=0
      - LINK_CONTRACT_ADDRESS=0xCfEB869F69431e42cdB54A4F4f105C19C080A601
      - CHAINLINK_TLS_PORT=0
      - SECURE_COOKIES=false
      - GAS_UPDATER_ENABLED=true
      - ALLOW_ORIGINS=*
      - ETH_URL=ws://ganache-stacktical:8545
      - DATABASE_URL=postgresql://postgres:password@postgres-stacktical:5432/chainlink?sslmode=disable

    command: local n -p /chainlink/.password -a /chainlink/.api
    networks:
      - dsla-test
    depends_on:
      - ganache-stacktical
      - postgres-stacktical
    restart: on-failure

networks:
    dsla-test:

volumes:
    postgres:
    chainlink:
